"""Initial migration

Revision ID: e417df46cf82
Revises: 
Create Date: 2026-05-09 21:00:22.468888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e417df46cf82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_cache_cache_key'), 'model_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_model_cache_expires_at'), 'model_cache', ['expires_at'], unique=False)
    op.create_index('ix_model_cache_model_expires', 'model_cache', ['model_name', 'expires_at'], unique=False)
    op.create_index(op.f('ix_model_cache_model_name'), 'model_cache', ['model_name'], unique=False)
    op.create_table('system_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('successful_requests', sa.Integer(), nullable=False),
    sa.Column('failed_requests', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('min_latency_ms', sa.Float(), nullable=True),
    sa.Column('max_latency_ms', sa.Float(), nullable=True),
    sa.Column('cpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('memory_usage_percent', sa.Float(), nullable=True),
    sa.Column('gpu_usage_percent', sa.Float(), nullable=True),
    sa.Column('model_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='usertier'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    op.create_table('api_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_date'), 'api_usage', ['date'], unique=False)
    op.create_index('ix_api_usage_user_date', 'api_usage', ['user_id', 'date'], unique=True)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.create_table('inference_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_total', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='requeststatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inference_requests_celery_task_id'), 'inference_requests', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_inference_requests_created_at'), 'inference_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_inference_requests_id'), 'inference_requests', ['id'], unique=False)
    op.create_index('ix_inference_requests_model_created', 'inference_requests', ['model_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_inference_requests_model_name'), 'inference_requests', ['model_name'], unique=False)
    op.create_index(op.f('ix_inference_requests_status'), 'inference_requests', ['status'], unique=False)
    op.create_index('ix_inference_requests_status_created', 'inference_requests', ['status', 'created_at'], unique=False)
    op.create_index('ix_inference_requests_user_created', 'inference_requests', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_inference_requests_user_id'), 'inference_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inference_requests_user_id'), table_name='inference_requests')
    op.drop_index('ix_inference_requests_user_created', table_name='inference_requests')
    op.drop_index('ix_inference_requests_status_created', table_name='inference_requests')
    op.drop_index(op.f('ix_inference_requests_status'), table_name='inference_requests')
    op.drop_index(op.f('ix_inference_requests_model_name'), table_name='inference_requests')
    op.drop_index('ix_inference_requests_model_created', table_name='inference_requests')
    op.drop_index(op.f('ix_inference_requests_id'), table_name='inference_requests')
    op.drop_index(op.f('ix_inference_requests_created_at'), table_name='inference_requests')
    op.drop_index(op.f('ix_inference_requests_celery_task_id'), table_name='inference_requests')
    op.drop_table('inference_requests')
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index('ix_api_usage_user_date', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_date'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_model_cache_model_name'), table_name='model_cache')
    op.drop_index('ix_model_cache_model_expires', table_name='model_cache')
    op.drop_index(op.f('ix_model_cache_expires_at'), table_name='model_cache')
    op.drop_index(op.f('ix_model_cache_cache_key'), table_name='model_cache')
    op.drop_table('model_cache')
    # ### end Alembic commands ###
